### ISSUE TITLE
Translations from Crowdin are not shown in the app

### ISSUE THREAD

**Issue by MrXlebNick** [crowdin/mobile-sdk-android#44] opened 2020-03-31 11:27 UTC
**Describe the bug**
Translations are not shown in the app

**To Reproduce**
1. Install Crowdin (config below)
2. Translate and approve a string in the Crowdin web interface
3. Click Content Delivery -> Distribution -> Release
4. Wait fo 15 minutes
5. 

**Expected behavior**
The string displayed is the one that comes from Crowdin

**Actual behavior**
The string displayed is the one that was built in

**Smartphone (please complete the following information):**
 - Huawei Honor 9, Android 9.0
 - Nexus 5X (emulator), Android 9.0

The built-in string has this warning:
>"fragmentPrivateSetupCodeInUse" is not translated in "de" (German), ...

Via debugging I see that the strings are being sent from Crowdin and stored in local and persistent repos, but `getString` is never called

My config:
```
// App.kt

    override fun attachBaseContext(base: Context?) {
        val newBase = base?.run { Crowdin.wrapContext(this) }
        super.attachBaseContext(newBase)
    }

    private fun initCrowdin() {
        Crowdin.init(applicationContext,
            CrowdinConfig.Builder()
                .withDistributionHash(applicationContext.getString(R.string.crowdin_distribution_hash))
                .withNetworkType(NetworkType.ALL)
                .withAuthConfig(
                    AuthConfig(
                        applicationContext.getString(R.string.crowdin_client_id),
                        applicationContext.getString(R.string.crowdin_client_secret),
                        null
                    )
                )
                .build())


        Crowdin.registerDataLoadingObserver(object: LoadingStateListener {
            override fun onDataChanged() {
                Log.d("***", "success")
            }

            override fun onFailure(throwable: Throwable) {
                Log.d("***", "fail", throwable)
            }

        })


        Crowdin.forceUpdate(applicationContext)
    }

// in code:
    ui.showError(R.string.fragmentPrivateSetupCodeInUse)
```

**Comment by MrXlebNick** [comment] 2020-03-31 11:41
I tried it with another string which is translated in all locales - same result

**Comment by og-fox** [comment] 2020-03-31 11:45
Hi @MrXlebNick,

Thanks a lot for all the details - already checking everything on our side! We'll get back with the news soon

**Comment by andrii-bodnar** [comment] 2020-03-31 14:09
Hi @MrXlebNick 

Try to override `attachBaseContext` method in `BaseActivity` class. If you don’t have `BaseActivity` class add the following code to all of your activities.

```
override fun attachBaseContext(newBase: Context) {
 super.attachBaseContext(Crowdin.wrapContext(newBase))
}
```

**Comment by MrXlebNick** [comment] 2020-03-31 15:15
Hi and thanks for your responses.
That actually helped with the string that had translations before, but not with the one that didn't. Is that so that it's impossible or did I miss something in configuration?

**Comment by andrii-bodnar** [comment] 2020-03-31 15:45
Actual behavior after changes with `attachBaseContext` is the same (The string displayed is the one that was built in) or different?

**Comment by MrXlebNick** [comment] 2020-03-31 16:00
No, after overriding `attachBaseContext` in Activity as well it resulted in this:

Target language (the one that is translated via Crowdin and the one the phone in) is Finnish.
Original language is English.

**Case 1: Built-in string exists original language only, in other `values-xx` this string is simply missing**
Expected behavior: show Finnish translations from Crowdin
Actual behavior: show text in original language :x: 

**Case 2: Built-in string exists in `values` and all `values-xx`, but the local Finnish translation is different from the one that comes from Crowdin**
Expected behavior: show Finnish translations from Crowdin
Actual behavior: matches expected result :heavy_check_mark:

**Comment by andrii-bodnar** [comment] 2020-03-31 16:07
Thanks a lot for the details - we will check on our side and get back with the updates

**Comment by andrii-bodnar** [comment] 2020-04-07 08:38
Hi @MrXlebNick !
Checked this on our side and we can't reproduce the first case. Could you please try the following:
- Close and reopen the Application or change the activity containing needed strings. It is the technical limitation on the Android side - we need to reload activity after translations download to display these translations.
- Check the `DataLoadingObserver` - if `onDataChanged` or `onFailure` functions are invoked. It may provide more information for debugging.

**Comment by MrXlebNick** [comment] 2020-04-10 23:06
Hello @andrii-bodnar and sorry for the late response!

`onDataChanged` is called, `onFailure` isn't.

Restarting the app didn't quite help, unfortunately

**Comment by Olena1234** [comment] 2020-04-10 23:10
Hi @MrXlebNick ! Thank you for the details, we are checking them on our side and will get back to you with updates

**Comment by MrXlebNick** [comment] 2020-04-10 23:20
Another issue that I discovered (I'm not sure if it's related to the current one, if not - please let me know and I'll re-file it as a separate issue):
A string from Crowdin isn't shown in the app after it was received by it.

Original language: English
Target language: Norwegian Bokmål

The default translation is present in the APK.

`attachBaseContext` is overridden both in Application class and in BaseActivity class (because both these contexts are used to get strings). When the first `attachBaseContext` is being called, `Crowdin.dataManager` is `null` and thus `wrapContext` doesn't really wrap context

**Comment by Olena1234** [comment] 2020-04-10 23:26
@MrXlebNick Thanks, looking into this as well!

**Comment by andrii-bodnar** [comment] 2020-04-13 06:49
Hi @MrXlebNick !

This repository contains an [example project](https://github.com/crowdin/mobile-sdk-android/tree/master/example), could you please reproduce these issues on it? 

This will help us to reproduce the problem on our side.

**Comment by MrXlebNick** [comment] 2020-04-21 07:45
Hello, I am trying to reproduce the issue on the example project. Should I create a separate Crowdin account for this or how do I simulate the case?

**Comment by crowdin-support** [comment] 2020-04-21 07:46
Hello,

Our replies might be a bit slower due to Easter holidays till April, 21 but
we will do our best to help you within 12 hours. Any urgent inquiries will
be resolved with the highest priority.

--
Sincerely,
Crowdin Team
{#HS:1142906893-111348#}

**Comment by andrii-bodnar** [comment] 2020-04-21 07:50
Hello, @MrXlebNick !
You don't need to create a separate account. You can create a new project or use the existing one by uploading source files from example project and creating a new distribution.

**Comment by crowdin-support** [comment] 2020-04-21 07:50
Hello,

Our replies might be a bit slower due to Easter holidays till April, 21 but
we will do our best to help you within 12 hours. Any urgent inquiries will
be resolved with the highest priority.

--
Sincerely,
Crowdin Team
{#HS:1142909765-111353#}

**Closed** 2020-07-06 07:19 UTC
Labels: bug, question
